### ISSUE TITLE
User error reporting

### ISSUE THREAD

**Issue by ehmicky** [colbyfayock/netlify-plugin-cloudinary#14]
This plugin is throwing errors to report user errors. However, uncaught exceptions in Build plugins are reported as plugin errors. Instead, [the `utils.build.failBuild()` utility function](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#error-reporting) should be used so the errors are reported as user-caused in the Netlify UI.

**Comment by ehmicky** [comment]
Whether the plugin or the whole build should be failed depends on whether it is acceptable for users to deploy their site even if the plugin failed. For example, for an analytics-related plugin, it might be the case. In the case of this plugin, images of the site would not be optimized and delivered by Cloudinary. I am leaning towards thinking this might be a case where the build should fail. Also for the reason you mentioned: if only the plugin was failed (not the build), missing inputs (such as cloudname) might be missed by users who do not check their build logs. What do you think?

Please note that both `utils.build.failBuild()` and throwing an error fail the build. The only difference is how the error is reported in the Netlify UI: as a user error or as a plugin error.

**Comment by colbyfayock** [comment]
cool thanks for the input @ehmicky
