### ISSUE TITLE
Environment variable `CLOUDINARY_ASSETS`

### ISSUE THREAD

**Issue by ehmicky** [colbyfayock/netlify-plugin-cloudinary#15]
The `CLOUDINARY_ASSETS` environment variable is currently used to pass information between the different event handlers of this plugin. Would it make more sense to use a variable at the top-level scope of the main file instead?

One difference is: environment variable values should be strings, whereas the value of this variable is currently an object. Also, environment variables added by plugins can be seen in the build command. In this case, I think the value would be `[object Object]` since I believe Node.js would serialize it using `String()`.

**Comment by colbyfayock** [comment]
great question, i wasn't sure if it would be maintained within the same node process, eaning, wasn't sure if i would be able to technically store and use data that way. is that the recommended approach? if that is the case, i may be able to simplify other things too, but i originally didnt want to make that assumption

**Comment by colbyfayock** [comment]
fixed this in https://github.com/colbyfayock/netlify-plugin-cloudinary/commit/128ebeaded48e8d2ce5ee6ad16e3e53ed0fd6614
