### ISSUE TITLE
Implement Semantic Release

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/netlify-plugin-cloudinary#21]
Add Semantic Release to automate versioning and management

https://github.com/semantic-release/semantic-release

**Comment by donno2048** [comment]
I would like to do it

**Comment by colbyfayock** [comment]
all you! :)

**Comment by colbyfayock** [comment]
Fixed by https://github.com/colbyfayock/netlify-plugin-cloudinary/pull/24
