### ISSUE TITLE
Issue Template is missing from this project.

### ISSUE THREAD

**Issue by Kunal-8789** [colbyfayock/netlify-plugin-cloudinary#27]
Hi @colbyfayock ,

I was just going through this project  and saw Issue Template is missing, as per [Github Community Standards recommendations](https://github.com/colbyfayock/next-cloudinary/community) that would make the project contributor friendly.

Let me know if this is something you would allow me to implement under Hacktoberfest.

**Comment by colbyfayock** [comment]
sounds good @Kunal-8789 

I had offered @orama254 to do the same work they did in https://github.com/colbyfayock/next-cloudinary/pull/12 

but i think it would be fair to let you do it to share the Issues

can you follow along with what they did in that pull request? feel free to make additions or provide feedback to the other PR but i'd like them to follow the same pattern

thanks

**Comment by Kunal-8789** [comment]
ok ,I understood. His issue template looks fine to me.

**Comment by colbyfayock** [comment]
cool, feel free to copy those over in a new PR
