### ISSUE TITLE
[Bug] Can't get upload preset to work

### ISSUE THREAD

**Issue by cynthiateeters** [colbyfayock/netlify-plugin-cloudinary#43]
# **Bug Report**

## **Describe the bug**

I am doing the Arcane Wiki tutorial with the added feature of using a preset.

I am using Netlify environment variables for Cloud Name, API key, and API Secret

and this is my netlify.toml file

```
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "YOUR_CLOUDNAME"
  deliveryType = "upload"
  uploadPreset = "arcane"
```

Here is my Cloudinary account showing the arcane preset

<img width="832" alt="Screenshot 2022-11-01 at 11 17 16 AM" src="https://user-images.githubusercontent.com/13385801/199295704-05a590fe-8909-49ee-8373-7a6dad4a3610.png">

Here is what I get upon deploy

<img width="855" alt="Screenshot 2022-11-01 at 11 20 41 AM" src="https://user-images.githubusercontent.com/13385801/199295784-94ed420b-3cb3-4d49-bd6d-a9c80cd97bb4.png">

## **Is this a regression?**

I'm pretty sure I got upload preset working over the summer with a test blog I was working with.

## **Steps To Reproduce the error**

1.
2.
3.
4.

### **Your environment**

- OS: 
- Node version:
- Npm version:
- Browser name and version:

**Comment by colbyfayock** [comment]
hey @cynthiateeters does the upload preset exist on the Cloudinary account you're using?

judging by the error I see there, it looks like it's successfully trying to use it, but its not finding it

**Comment by cynthiateeters** [comment]
Right, I set it as a named transformation and from there I made it a preset.

<img width="962" alt="Screenshot 2022-11-01 at 10 02 16 PM" src="https://user-images.githubusercontent.com/13385801/199377598-59c39929-8fbf-4eed-bffa-c5e89a871ed2.png">

**Comment by colbyfayock** [comment]
ah - honsetly im not too familiar with that, but that's a different feature

Upload Presets are under Settings > Upload > Upload Presets

<img width="928" alt="image" src="https://user-images.githubusercontent.com/1045274/199379594-0590ec31-6ef5-45cd-9a9d-c37bdfb050cd.png">

**Comment by cynthiateeters** [comment]
Oh!!!

Let me take a look at that.

**Comment by cynthiateeters** [comment]
That's what was the problem. Thanks.
