### ISSUE TITLE
[Bug] Uses URL with "main--" at the start resulting in invalid URL 

### ISSUE THREAD

**Issue by L8X** [colbyfayock/netlify-plugin-cloudinary#45]
The plugin is generating images via https://main--whatever.netlify.app instead of the correct https://whatever.netlify.app resulting in cloudinary rejecting the image and returning 401.

Please correct this to use either the custom domain or the domain minus main--.

**Comment by colbyfayock** [comment]
hey @L8X apologies on the delay, but this should now be addressed in the upcoming release!

**Comment by colbyfayock** [comment]
actually looking at my demo build it doesnt look like it resolved it
