### ISSUE TITLE
Handle image replacement in srcset

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/netlify-plugin-cloudinary#8]
Currently only looking inside the `src` property on images, should be additionally handling images within `srcset`

**Comment by shikhar13012001** [comment]
Hi @colbyfayock I am interested in this issue, Can you please assign this to me ?
Thanks.

**Comment by colbyfayock** [comment]
sure thing!

**Comment by shikhar13012001** [comment]
Hi @colbyfayock, thanks for assigning this issue to me. Can you also guide me on how should I approach this issue? such as what files to target.
Thanks!

**Comment by colbyfayock** [comment]
yup no problem

the plugin root is `src/index.js` where on this line, we run a function that takes in the HTML and configuration:

https://github.com/colbyfayock/netlify-plugin-cloudinary/blob/main/src/index.js#L192

once there, JS Dom is used to create a "virtual dom" where all images are queried, looped through, and modified

the Cloudinary URL is determined and then the image's source is updated with:

https://github.com/colbyfayock/netlify-plugin-cloudinary/blob/19cb04fcc20c82d749e9c3a2fcbd9b5ffd940571/src/lib/cloudinary.js#L227

we need to have the use case covered where someone is including a `srcset` in addition to the `src`:

```
<img src="elva-fairy-800w.jpg" alt="Elva dressed as a fairy" />
```
vs
```
<img
  srcset="elva-fairy-480w.jpg 480w, elva-fairy-800w.jpg 800w"
  sizes="(max-width: 600px) 480px,
         800px"
  src="elva-fairy-800w.jpg"
  alt="Elva dressed as a fairy" />
```

so that should end up being:

```
<img
  srcset="https://res.cloudinary.com/.../elva-fairy-480w.jpg 480w, https://res.cloudinary.com/.../elva-fairy-800w.jpg 800w"
  sizes="(max-width: 600px) 480px,
         800px"
  src="https://res.cloudinary.com/.../elva-fairy-800w.jpg"
  alt="Elva dressed as a fairy" />
```

> Example pulled from MDN. More info about [srcset and responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes)

the image replacement mechanism should function the same with the main difference is the `srcset` attribute will include multiple 

does that all make sense?

**Comment by colbyfayock** [comment]
i recommend and encourage writing a few test cases inside of this that includes examples of using srcset to both ensure it works but also as an easier way to test the plugin while developing

https://github.com/colbyfayock/netlify-plugin-cloudinary/blob/main/tests/lib/cloudinary.test.js#L87

**Comment by shikhar13012001** [comment]
Hi @colbyfayock thanks explaining so clearly, sorry for late reply I got caught with college stuff, I would sure give it a try, Can I also ask you doubts if I get stuck (I do often ;) )?

**Comment by shikhar13012001** [comment]
Hi @colbyfayock, I have written the part to format the `srcset` URLs but I am unable to right the assertiveness of the test, although a simple console.log statement confirms the conversion to Cloudinary URL.
Can you please guide me a bit here as well?

**Comment by colbyfayock** [comment]
always ahppy to answer questions i can :) did so in the PR so far

**Comment by colbyfayock** [comment]
@shikhar13012001 we can close this Issue right?

**Comment by colbyfayock** [comment]
closing, let me konw if it needs to be re-opened

**Comment by shikhar13012001** [comment]
Yes , I think it is completed. @colbyfayock thanks again.
